name: Vertigo
description: Vertigo Minigame
authors: [ feydk, StarTux ]
version: 1.0
api-version: 1.18
website: https://cavetale.com
main: io.github.feydk.vertigo.VertigoLoader
depend: [Core, PlayerCache, Mytems, Title, Sidebar, Fam]
softdepend: []
commands:
  vertigo:
    description: Join a game of Vertigo
    permission: vertigo.vertigo
    usage: /vertigo
  vertigoadmin:
    aliases: [vertigoadm]
    description: Vertigo admin interface
    permission: vertigo.admin
    usage: |-
      /vertigo
      /vertigoadmin load <world name> - Load a world
      /vertigoadmin setup - Prepare the game world
      /vertigoadmin ready - Set game state to ready
      /vertigoadmin announce - Announce a ready game
      /vertigoadmin start - Begin the game
      /vertigoadmin stop - End the game
      /vertigoadmin spectate - Spectate the game
      /vertigoadmin discard - Discards game and world
      /vertigoadmin reset - Reset the game
      /vertigoadmin kickplayers - Kick all remaining players
      /vertigoadmin event true|false - Set event mode
permissions: {}